apiVersion: v1
kind: ConfigMap
metadata:
  name: fraud-detection-config
  namespace: fraud-detection
  labels:
    app.kubernetes.io/part-of: fraud-detection-pipeline
data:
  KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
  REDIS_HOST: "redis"
  REDIS_PORT: "6379"
  REDIS_PASSWORD: ""
  DB_URL: "jdbc:postgresql://postgres:5432/frauddb"
  DB_USERNAME: "fraud"
